# Generated by Django 3.0.6 on 2020-11-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201113_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
