# Generated by Django 3.1.2 on 2020-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201109_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FilePathField(path='C:\\Users\\keireth\\Desktop\\jhonny\\Development\\web projects\\personal website\\personalweb\\media'),
        ),
    ]
